update

diff --git a/.github/diy/patches/advancedplus.patch b/.github/diy/patches/advancedplus.patch
--- a/.github/diy/patches/advancedplus.patch
+++ b/.github/diy/patches/advancedplus.patch
@@ -1,33 +1,290 @@
---- a/luci-app-advancedplus/root/etc/init.d/advancedplus
-+++ b/luci-app-advancedplus/root/etc/init.d/advancedplus
-@@ -352,7 +352,6 @@ uci commit advancedplus
- start() {
-     [ "x$(uci -q get advancedplus.@basic[0].mode)" = "x" ]  && /etc/config/advancedplus reset 
-     kucatset
--    advancedset
-     rm -rf /tmp/luci-*
- }
+--- a/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
++++ b/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
+@@ -184,7 +184,7 @@ function parseList(s, dest)
+ 			val = RegExp.$2.trim();
+ 		}
+ 		else if (pkg) {
+-			dest.pkgs[pkg.name] = pkg;
++			dest.pkgs[pkg.name] = dest.pkgs[pkg.name] ? dest.pkgs[pkg.name] : pkg;
  
+ 			var provides = dest.providers[pkg.name] ? [] : [ pkg.name ];
+ 
+@@ -248,7 +248,7 @@ function display(pattern)
+ 			var avail = packages.available.pkgs[name],
+ 			    inst  = packages.installed.pkgs[name];
+ 
+-			if (!inst || !inst.installed)
++			if (!inst || !inst.installed || pkg.name.includes('kmod-') || pkg.name.includes('busybox') || pkg.name.includes('base-files'))
+ 				continue;
+ 
+ 			if (!avail || compareVersion(avail.version, pkg.version) <= 0)
+@@ -261,6 +261,7 @@ function display(pattern)
+ 			btn = E('div', {
+ 				'class': 'btn cbi-button-positive',
+ 				'data-package': name,
++				'action': 'upgrade',
+ 				'click': handleInstall
+ 			}, _('Upgrade…'));
+ 		}
+@@ -284,12 +285,14 @@ function display(pattern)
+ 				btn = E('div', {
+ 					'class': 'btn cbi-button-action',
+ 					'data-package': name,
++					'action': 'install',
+ 					'click': handleInstall
+ 				}, _('Install…'));
+-			else if (inst.installed && inst.version != pkg.version)
++			else if (inst.installed && compareVersion(pkg.version, inst.version) > 0)
+ 				btn = E('div', {
+ 					'class': 'btn cbi-button-positive',
+ 					'data-package': name,
++					'action': 'upgrade',
+ 					'click': handleInstall
+ 				}, _('Upgrade…'));
+ 			else
+@@ -393,6 +396,12 @@ function handleMode(ev)
+ 
+ 	currentDisplayMode = tab.getAttribute('data-mode');
+ 
++	if (currentDisplayMode == "updates"){
++	var filterv = document.querySelector('input[name="filter"]')
++	if ( filterv.value == "luci-app-")
++		filterv.value = ""
++	}
++
+ 	display(document.querySelector('input[name="filter"]').value);
+ 
+ 	ev.target.blur();
+@@ -661,6 +670,7 @@ function handleReset(ev)
+ function handleInstall(ev)
+ {
+ 	var name = ev.target.getAttribute('data-package'),
++	    action = ev.target.getAttribute('action'),
+ 	    pkg = packages.available.pkgs[name],
+ 	    depcache = {},
+ 	    size;
+@@ -786,7 +796,8 @@ function handleInstall(ev)
+ 						'id': 'overwrite-cb',
+ 						'type': 'checkbox',
+ 						'name': 'overwrite',
+-						'disabled': isReadonlyView
++						'disabled': isReadonlyView,
++						'checked': true
+ 					}), ' ',
+ 					E('label', { 'for': 'overwrite-cb' }), ' ',
+ 					_('Allow overwriting conflicting package files')
+@@ -800,7 +811,7 @@ function handleInstall(ev)
+ 			}, _('Cancel')),
+ 			' ',
+ 			E('div', {
+-				'data-command': 'install',
++				'data-command': action,
+ 				'data-package': name,
+ 				'class': 'btn cbi-button-action',
+ 				'click': handleOpkg,
+@@ -1000,7 +1011,8 @@ function handleOpkg(ev)
+ 
+ 		fs.exec_direct('/usr/libexec/opkg-call', argv, 'json').then(function(res) {
+ 			dlg.removeChild(dlg.lastChild);
+-
++			var showModalFlag = (cmd !== 'update' && pkg) || res.stderr;
++			if (showModalFlag) {
+ 			if (res.stdout)
+ 				dlg.appendChild(E('pre', [ res.stdout ]));
+ 
+@@ -1028,6 +1040,10 @@ function handleOpkg(ev)
+ 							resolveFn(res);
+ 					}, this, res)
+ 				}, _('Dismiss'))));
++			} else {
++				ui.hideModal();
++				updateLists();
++			}
+ 		}).catch(function(err) {
+ 			ui.addNotification(null, E('p', _('Unable to execute <em>opkg %s</em> command: %s').format(cmd, err)));
+ 			ui.hideModal();
+@@ -1122,6 +1138,36 @@ return view.extend({
+ 	},
+ 
+ 	render: function(listData) {
++		var checkUpdateNeeded = function() {
++            return Promise.all([
++                L.resolveDefault(fs.stat('/tmp/opkg-lists/openwrt_base'), null),
++                L.resolveDefault(fs.read('/tmp/resolv.conf.d/resolv.conf.auto'), '')
++            ]).then(function(results) {
++                var stat = results[0];
++                var resolvContent = results[1];
++
++                // 检查 /tmp/opkg-lists 的更新时间
++                var needTimeUpdate = false;
++                if (!stat) {
++                    needTimeUpdate = true; // 如果文件夹不存在，需要更新
++                } else {
++                    var currentTime = Math.floor(Date.now() / 1000);
++                    var lastUpdateTime = stat.mtime;
++                    var timeDifference = currentTime - lastUpdateTime;
++                    needTimeUpdate = timeDifference > 21600; // 如果超过1小时，需要更新
++                }
++
++                // 检查 resolv.conf.auto 文件内容
++                var hasResolvContent = resolvContent && resolvContent.trim().length > 0;
++
++                // 只有当需要时间更新且 resolv.conf.auto 不为空时，才返回 true
++                return needTimeUpdate && hasResolvContent;
++            }).catch(function(error) {
++                console.error('Error checking update status:', error);
++                return false; // 如果出错，不执行更新
++            });
++        };
++
+ 		var query = decodeURIComponent(L.toArray(location.search.match(/\bquery=([^=]+)\b/))[1] || '');
+ 
+ 		var view = E([], [
+@@ -1138,7 +1184,7 @@ return view.extend({
+ 				E('div', {}, [
+ 					E('label', {}, _('Filter') + ':'),
+ 					E('span', { 'class': 'control-group' }, [
+-						E('input', { 'type': 'text', 'name': 'filter', 'placeholder': _('Type to filter…'), 'value': query, 'input': handleInput }),
++						E('input', { 'type': 'text', 'name': 'filter', 'placeholder': _('Type to filter…'), 'value': 'luci-app-', 'input': handleInput }),
+ 						E('button', { 'class': 'btn cbi-button', 'click': handleReset }, [ _('Clear') ])
+ 					])
+ 				]),
+@@ -1155,6 +1201,7 @@ return view.extend({
+ 					E('label', {}, _('Actions') + ':'), ' ',
+ 					E('span', { 'class': 'control-group' }, [
+ 						E('button', { 'class': 'btn cbi-button-positive', 'data-command': 'update', 'click': handleOpkg, 'disabled': isReadonlyView }, [ _('Update lists…') ]), ' ',
++						E('button', { 'class': 'btn cbi-button-negative', 'data-command': 'upgradeall', 'click': handleOpkg, 'disabled': isReadonlyView }, [ _('Upgrade all…') ]), ' ',
+ 						E('button', { 'class': 'btn cbi-button-action', 'click': handleUpload, 'disabled': isReadonlyView }, [ _('Upload Package…') ]), ' ',
+ 						E('button', { 'class': 'btn cbi-button-neutral', 'click': handleConfig }, [ _('Configure opkg…') ])
+ 					])
+@@ -1240,7 +1287,17 @@ return view.extend({
+ 		]);
+ 
+ 		requestAnimationFrame(function() {
+-			updateLists(listData)
++			updateLists(listData);
++            checkUpdateNeeded().then(function(needUpdate) {
++                if (needUpdate) {
++					setTimeout(function() {
++                    var updateButton = document.querySelector('button[data-command="update"]');
++                    if (updateButton) {
++                        updateButton.click();
++                    }
++					}, 10)
++                }
++            });
+ 		});
+ 
+ 		return view;
 
---- a/luci-app-advancedplus/luasrc/controller/advancedplus.lua
-+++ b/luci-app-advancedplus/luasrc/controller/advancedplus.lua
-@@ -20,10 +20,9 @@ function index()
- 	page.acl_depends = { "luci-app-advancedplus" }
- 	
- 	entry({"admin","system","advancedplus","advancededit"},cbi("advancedplus/advancededit"),_("Advanced Edit"),10).leaf = true
--	entry({"admin","system","advancedplus","advancedset"},cbi("advancedplus/advancedset"),_("Advanced Setting"),20).leaf = true
--	entry({"admin","system","advancedplus","advancedipk"},cbi("advancedplus/advancedipk", {hideapplybtn=true, hidesavebtn=true, hideresetbtn=true}),_("Loading plugins"),30).leaf = true
- 	if nixio.fs.access('/www/luci-static/kucat/css/style.css') then
- 	    entry({"admin","system","advancedplus","kucatset"},cbi("advancedplus/kucatset"),_("KuCat Theme Config"),40).leaf = true
-+	    entry({"admin", "system","advancedplus","kucatupload"}, form("advancedplus/kucatupload"), _("Desktop background upload"), 80).leaf = true
- 	end
- 	if nixio.fs.access('/www/luci-static/argon/css/cascade.css') then
- 	    entry({"admin", "system", "advancedplus","argon-config"}, form("advancedplus/argon-config"), _("Argon Config"), 50).leaf = true
-@@ -32,7 +31,6 @@ function index()
- 	    entry({"admin", "system",  "advancedplus","design-config"}, form("advancedplus/design-config"), _("Design Config"), 60).leaf = true
- 	end
- 	entry({"admin", "system","advancedplus","upload"}, form("advancedplus/upload"), _("Login Background Upload"), 70).leaf = true
--	entry({"admin", "system","advancedplus","kucatupload"}, form("advancedplus/kucatupload"), _("Desktop background upload"), 80).leaf = true
- 	
+--- a/luci-app-opkg/root/usr/libexec/opkg-call
++++ b/luci-app-opkg/root/usr/libexec/opkg-call
+@@ -13,7 +13,7 @@ case "$action" in
+ 		lists_dir=$(sed -rne 's#^lists_dir \S+ (\S+)#\1#p' /etc/opkg.conf /etc/opkg/*.conf 2>/dev/null | tail -n 1)
+ 		find "${lists_dir:-/usr/lib/opkg/lists}" -type f '!' -name '*.sig' | xargs -r gzip -cd
+ 	;;
+-	install|update|remove)
++	install|update|upgrade|upgradeall|remove)
+ 		(
+ 			opkg="opkg"
  
- 	entry({"admin", "system", "advancedplus", "advancedrun"}, call("advanced_run"))
+@@ -33,10 +33,45 @@ case "$action" in
+ 			done
+ 
+ 			if flock -x 200; then
+-				$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
+-				code=$?
+-				stdout=$(cat /tmp/opkg.out)
++				if [ $action == "upgradeall" ]; then
++					opkg update </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
++					code=$?
++					if [ $code == 0 ]; then
++						. /etc/profile.d/opkg.sh
++						if [[ "$(cat `opkg export au`)" ]] && lock -n /var/lock/opkg-upgrade; then
++						 opkg upgr </dev/null >>/tmp/opkg.out 2>>/tmp/opkg.err
++						 code=$?
++						 lock -u /var/lock/opkg-upgrade
++						else
++							echo "🎉 所有软件包已是最新~" >>/tmp/opkg.out
++							code=0
++						fi
++					fi
++				else
++					$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
++					code=$?
++				fi
++				pkgn="$(echo $@ | cut -d - -f 3-)"
++				case "$action" in
++					install|upgrade)
++					if [ "$(opkg list-installed | cut -f 1 -d ' ' | grep -w $@)" ]; then
++							rm -f /tmp/opkg.err
++							([ -f /etc/profile.d/opkg.sh ] && . /etc/profile.d/opkg.sh && opkg save) &
++					fi
++					;;
++					remove)
++						if [ ! "$(opkg list-installed | cut -f 1 -d ' ' | grep -w $@)" ]; then
++							rm -f /tmp/opkg.err
++							([ -f /etc/profile.d/opkg.sh ] && . /etc/profile.d/opkg.sh && opkg save) &
++						fi
++					;;
++				esac
+ 				stderr=$(cat /tmp/opkg.err)
++				[ -n "$stderr" ] || {
++					echo "🎉 已完成, 请关闭本窗口~" >>/tmp/opkg.out
++					code=0
++				}
++				stdout=$(cat /tmp/opkg.out)
+ 			else
+ 				code=255
+ 				stderr="Failed to acquire lock"
+@@ -53,7 +88,7 @@ case "$action" in
+ 	;;
+ 	*)
+ 		echo "Usage: $0 {list-installed|list-available}"       >&2
+-		echo "       $0 {install|upgrade|remove} pkg[ pkg...]" >&2
++		echo "       $0 {install|upgrade|upgradeall|remove} pkg[ pkg...]" >&2
+ 		exit 1
+ 	;;
+ esac
+
+--- a/luci-app-opkg/root/usr/share/rpcd/acl.d/luci-app-opkg.json
++++ b/luci-app-opkg/root/usr/share/rpcd/acl.d/luci-app-opkg.json
+@@ -9,6 +9,7 @@
+ 				"/usr/libexec/opkg-call list-installed": [ "exec" ],
+ 				"/usr/libexec/opkg-call list-available": [ "exec" ],
+ 				"/etc/opkg.conf": [ "read" ],
++				"/tmp/resolv.conf.d/resolv.conf.auto": [ "read" ],
+ 				"/etc/opkg/*.conf": [ "read" ]
+ 			},
+ 			"ubus": {
+@@ -20,6 +21,8 @@
+ 				"/usr/libexec/opkg-call install *": [ "exec" ],
+ 				"/usr/libexec/opkg-call remove *": [ "exec" ],
+ 				"/usr/libexec/opkg-call update *": [ "exec" ],
++				"/usr/libexec/opkg-call upgrade *": [ "exec" ],
++				"/usr/libexec/opkg-call upgradeall *": [ "exec" ],
+ 				"/etc/opkg.conf": [ "write" ],
+ 				"/etc/opkg/*.conf": [ "write" ],
+ 				"/tmp/upload.ipk": [ "write" ]
+
+--- a/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
++++ b/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
+@@ -261,6 +261,7 @@ return view.extend({
+ 					body.push(E('p', {}, E('label', { 'class': 'btn' }, [
+ 						opts.backup_pkgs[0], ' ', _('Include in backup a list of current installed packages at /etc/backup/installed_packages.txt')
+ 					])));
++					opts.backup_pkgs[0].checked = true;
+ 				};
+ 
+ 				var cntbtn = E('button', {
+@@ -302,6 +303,10 @@ return view.extend({
+ 				opts.keep[0].addEventListener('change', function(ev) {
+ 					opts.skip_orig[0].disabled = !ev.target.checked;
+ 					opts.backup_pkgs[0].disabled = !ev.target.checked;
++					if (ev.target.checked == false){
++						opts.skip_orig[0].checked =false
++						opts.backup_pkgs[0].checked =false
++					}
+ 
+ 				});
+ 
diff --git a/.github/diy/patches/depends.patch b/.github/diy/patches/depends.patch
--- a/.github/diy/patches/depends.patch
+++ b/.github/diy/patches/depends.patch
@@ -1,183 +1,290 @@
---- a/luci-app-aria2/Makefile
-+++ b/luci-app-aria2/Makefile
-@@ -7,7 +7,7 @@
- include $(TOPDIR)/rules.mk
+--- a/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
++++ b/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
+@@ -184,7 +184,7 @@ function parseList(s, dest)
+ 			val = RegExp.$2.trim();
+ 		}
+ 		else if (pkg) {
+-			dest.pkgs[pkg.name] = pkg;
++			dest.pkgs[pkg.name] = dest.pkgs[pkg.name] ? dest.pkgs[pkg.name] : pkg;
  
- LUCI_TITLE:=LuCI Support for Aria2
--LUCI_DEPENDS:=+aria2
-+LUCI_DEPENDS:=+aria2 +ariang
- LUCI_PKGARCH:=all
+ 			var provides = dest.providers[pkg.name] ? [] : [ pkg.name ];
  
- PKG_MAINTAINER:=Xingwang Liao <kuoruan@gmail.com>
+@@ -248,7 +248,7 @@ function display(pattern)
+ 			var avail = packages.available.pkgs[name],
+ 			    inst  = packages.installed.pkgs[name];
+ 
+-			if (!inst || !inst.installed)
++			if (!inst || !inst.installed || pkg.name.includes('kmod-') || pkg.name.includes('busybox') || pkg.name.includes('base-files'))
+ 				continue;
+ 
+ 			if (!avail || compareVersion(avail.version, pkg.version) <= 0)
+@@ -261,6 +261,7 @@ function display(pattern)
+ 			btn = E('div', {
+ 				'class': 'btn cbi-button-positive',
+ 				'data-package': name,
++				'action': 'upgrade',
+ 				'click': handleInstall
+ 			}, _('Upgrade…'));
+ 		}
+@@ -284,12 +285,14 @@ function display(pattern)
+ 				btn = E('div', {
+ 					'class': 'btn cbi-button-action',
+ 					'data-package': name,
++					'action': 'install',
+ 					'click': handleInstall
+ 				}, _('Install…'));
+-			else if (inst.installed && inst.version != pkg.version)
++			else if (inst.installed && compareVersion(pkg.version, inst.version) > 0)
+ 				btn = E('div', {
+ 					'class': 'btn cbi-button-positive',
+ 					'data-package': name,
++					'action': 'upgrade',
+ 					'click': handleInstall
+ 				}, _('Upgrade…'));
+ 			else
+@@ -393,6 +396,12 @@ function handleMode(ev)
+ 
+ 	currentDisplayMode = tab.getAttribute('data-mode');
+ 
++	if (currentDisplayMode == "updates"){
++	var filterv = document.querySelector('input[name="filter"]')
++	if ( filterv.value == "luci-app-")
++		filterv.value = ""
++	}
++
+ 	display(document.querySelector('input[name="filter"]').value);
+ 
+ 	ev.target.blur();
+@@ -661,6 +670,7 @@ function handleReset(ev)
+ function handleInstall(ev)
+ {
+ 	var name = ev.target.getAttribute('data-package'),
++	    action = ev.target.getAttribute('action'),
+ 	    pkg = packages.available.pkgs[name],
+ 	    depcache = {},
+ 	    size;
+@@ -786,7 +796,8 @@ function handleInstall(ev)
+ 						'id': 'overwrite-cb',
+ 						'type': 'checkbox',
+ 						'name': 'overwrite',
+-						'disabled': isReadonlyView
++						'disabled': isReadonlyView,
++						'checked': true
+ 					}), ' ',
+ 					E('label', { 'for': 'overwrite-cb' }), ' ',
+ 					_('Allow overwriting conflicting package files')
+@@ -800,7 +811,7 @@ function handleInstall(ev)
+ 			}, _('Cancel')),
+ 			' ',
+ 			E('div', {
+-				'data-command': 'install',
++				'data-command': action,
+ 				'data-package': name,
+ 				'class': 'btn cbi-button-action',
+ 				'click': handleOpkg,
+@@ -1000,7 +1011,8 @@ function handleOpkg(ev)
+ 
+ 		fs.exec_direct('/usr/libexec/opkg-call', argv, 'json').then(function(res) {
+ 			dlg.removeChild(dlg.lastChild);
+-
++			var showModalFlag = (cmd !== 'update' && pkg) || res.stderr;
++			if (showModalFlag) {
+ 			if (res.stdout)
+ 				dlg.appendChild(E('pre', [ res.stdout ]));
+ 
+@@ -1028,6 +1040,10 @@ function handleOpkg(ev)
+ 							resolveFn(res);
+ 					}, this, res)
+ 				}, _('Dismiss'))));
++			} else {
++				ui.hideModal();
++				updateLists();
++			}
+ 		}).catch(function(err) {
+ 			ui.addNotification(null, E('p', _('Unable to execute <em>opkg %s</em> command: %s').format(cmd, err)));
+ 			ui.hideModal();
+@@ -1122,6 +1138,36 @@ return view.extend({
+ 	},
+ 
+ 	render: function(listData) {
++		var checkUpdateNeeded = function() {
++            return Promise.all([
++                L.resolveDefault(fs.stat('/tmp/opkg-lists/openwrt_base'), null),
++                L.resolveDefault(fs.read('/tmp/resolv.conf.d/resolv.conf.auto'), '')
++            ]).then(function(results) {
++                var stat = results[0];
++                var resolvContent = results[1];
++
++                // 检查 /tmp/opkg-lists 的更新时间
++                var needTimeUpdate = false;
++                if (!stat) {
++                    needTimeUpdate = true; // 如果文件夹不存在，需要更新
++                } else {
++                    var currentTime = Math.floor(Date.now() / 1000);
++                    var lastUpdateTime = stat.mtime;
++                    var timeDifference = currentTime - lastUpdateTime;
++                    needTimeUpdate = timeDifference > 21600; // 如果超过1小时，需要更新
++                }
++
++                // 检查 resolv.conf.auto 文件内容
++                var hasResolvContent = resolvContent && resolvContent.trim().length > 0;
++
++                // 只有当需要时间更新且 resolv.conf.auto 不为空时，才返回 true
++                return needTimeUpdate && hasResolvContent;
++            }).catch(function(error) {
++                console.error('Error checking update status:', error);
++                return false; // 如果出错，不执行更新
++            });
++        };
++
+ 		var query = decodeURIComponent(L.toArray(location.search.match(/\bquery=([^=]+)\b/))[1] || '');
+ 
+ 		var view = E([], [
+@@ -1138,7 +1184,7 @@ return view.extend({
+ 				E('div', {}, [
+ 					E('label', {}, _('Filter') + ':'),
+ 					E('span', { 'class': 'control-group' }, [
+-						E('input', { 'type': 'text', 'name': 'filter', 'placeholder': _('Type to filter…'), 'value': query, 'input': handleInput }),
++						E('input', { 'type': 'text', 'name': 'filter', 'placeholder': _('Type to filter…'), 'value': 'luci-app-', 'input': handleInput }),
+ 						E('button', { 'class': 'btn cbi-button', 'click': handleReset }, [ _('Clear') ])
+ 					])
+ 				]),
+@@ -1155,6 +1201,7 @@ return view.extend({
+ 					E('label', {}, _('Actions') + ':'), ' ',
+ 					E('span', { 'class': 'control-group' }, [
+ 						E('button', { 'class': 'btn cbi-button-positive', 'data-command': 'update', 'click': handleOpkg, 'disabled': isReadonlyView }, [ _('Update lists…') ]), ' ',
++						E('button', { 'class': 'btn cbi-button-negative', 'data-command': 'upgradeall', 'click': handleOpkg, 'disabled': isReadonlyView }, [ _('Upgrade all…') ]), ' ',
+ 						E('button', { 'class': 'btn cbi-button-action', 'click': handleUpload, 'disabled': isReadonlyView }, [ _('Upload Package…') ]), ' ',
+ 						E('button', { 'class': 'btn cbi-button-neutral', 'click': handleConfig }, [ _('Configure opkg…') ])
+ 					])
+@@ -1240,7 +1287,17 @@ return view.extend({
+ 		]);
+ 
+ 		requestAnimationFrame(function() {
+-			updateLists(listData)
++			updateLists(listData);
++            checkUpdateNeeded().then(function(needUpdate) {
++                if (needUpdate) {
++					setTimeout(function() {
++                    var updateButton = document.querySelector('button[data-command="update"]');
++                    if (updateButton) {
++                        updateButton.click();
++                    }
++					}, 10)
++                }
++            });
+ 		});
+ 
+ 		return view;
 
---- a/luci-app-samba4/Makefile
-+++ b//luci-app-samba4/Makefile
-@@ -3,7 +3,7 @@
- include $(TOPDIR)/rules.mk
+--- a/luci-app-opkg/root/usr/libexec/opkg-call
++++ b/luci-app-opkg/root/usr/libexec/opkg-call
+@@ -13,7 +13,7 @@ case "$action" in
+ 		lists_dir=$(sed -rne 's#^lists_dir \S+ (\S+)#\1#p' /etc/opkg.conf /etc/opkg/*.conf 2>/dev/null | tail -n 1)
+ 		find "${lists_dir:-/usr/lib/opkg/lists}" -type f '!' -name '*.sig' | xargs -r gzip -cd
+ 	;;
+-	install|update|remove)
++	install|update|upgrade|upgradeall|remove)
+ 		(
+ 			opkg="opkg"
  
- LUCI_TITLE:=Network Shares - Samba 4 SMB/CIFS fileserver
--LUCI_DEPENDS:=+samba4-server
-+LUCI_DEPENDS:=+samba4-server +autoshare-samba
+@@ -33,10 +33,45 @@ case "$action" in
+ 			done
  
- include ../../luci.mk
- 
+ 			if flock -x 200; then
+-				$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
+-				code=$?
+-				stdout=$(cat /tmp/opkg.out)
++				if [ $action == "upgradeall" ]; then
++					opkg update </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
++					code=$?
++					if [ $code == 0 ]; then
++						. /etc/profile.d/opkg.sh
++						if [[ "$(cat `opkg export au`)" ]] && lock -n /var/lock/opkg-upgrade; then
++						 opkg upgr </dev/null >>/tmp/opkg.out 2>>/tmp/opkg.err
++						 code=$?
++						 lock -u /var/lock/opkg-upgrade
++						else
++							echo "🎉 所有软件包已是最新~" >>/tmp/opkg.out
++							code=0
++						fi
++					fi
++				else
++					$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
++					code=$?
++				fi
++				pkgn="$(echo $@ | cut -d - -f 3-)"
++				case "$action" in
++					install|upgrade)
++					if [ "$(opkg list-installed | cut -f 1 -d ' ' | grep -w $@)" ]; then
++							rm -f /tmp/opkg.err
++							([ -f /etc/profile.d/opkg.sh ] && . /etc/profile.d/opkg.sh && opkg save) &
++					fi
++					;;
++					remove)
++						if [ ! "$(opkg list-installed | cut -f 1 -d ' ' | grep -w $@)" ]; then
++							rm -f /tmp/opkg.err
++							([ -f /etc/profile.d/opkg.sh ] && . /etc/profile.d/opkg.sh && opkg save) &
++						fi
++					;;
++				esac
+ 				stderr=$(cat /tmp/opkg.err)
++				[ -n "$stderr" ] || {
++					echo "🎉 已完成, 请关闭本窗口~" >>/tmp/opkg.out
++					code=0
++				}
++				stdout=$(cat /tmp/opkg.out)
+ 			else
+ 				code=255
+ 				stderr="Failed to acquire lock"
+@@ -53,7 +88,7 @@ case "$action" in
+ 	;;
+ 	*)
+ 		echo "Usage: $0 {list-installed|list-available}"       >&2
+-		echo "       $0 {install|upgrade|remove} pkg[ pkg...]" >&2
++		echo "       $0 {install|upgrade|upgradeall|remove} pkg[ pkg...]" >&2
+ 		exit 1
+ 	;;
+ esac
 
---- a/luci-app-ksmbd/Makefile
-+++ b/luci-app-ksmbd/Makefile
-@@ -3,7 +3,7 @@
- include $(TOPDIR)/rules.mk
- 
- LUCI_TITLE:=Network Shares - Ksmbd the SMB kernel fileserver
--LUCI_DEPENDS:=+ksmbd-server
-+LUCI_DEPENDS:=+ksmbd-server +autoshare-ksmbd
- 
- include ../../luci.mk
+--- a/luci-app-opkg/root/usr/share/rpcd/acl.d/luci-app-opkg.json
++++ b/luci-app-opkg/root/usr/share/rpcd/acl.d/luci-app-opkg.json
+@@ -9,6 +9,7 @@
+ 				"/usr/libexec/opkg-call list-installed": [ "exec" ],
+ 				"/usr/libexec/opkg-call list-available": [ "exec" ],
+ 				"/etc/opkg.conf": [ "read" ],
++				"/tmp/resolv.conf.d/resolv.conf.auto": [ "read" ],
+ 				"/etc/opkg/*.conf": [ "read" ]
+ 			},
+ 			"ubus": {
+@@ -20,6 +21,8 @@
+ 				"/usr/libexec/opkg-call install *": [ "exec" ],
+ 				"/usr/libexec/opkg-call remove *": [ "exec" ],
+ 				"/usr/libexec/opkg-call update *": [ "exec" ],
++				"/usr/libexec/opkg-call upgrade *": [ "exec" ],
++				"/usr/libexec/opkg-call upgradeall *": [ "exec" ],
+ 				"/etc/opkg.conf": [ "write" ],
+ 				"/etc/opkg/*.conf": [ "write" ],
+ 				"/tmp/upload.ipk": [ "write" ]
 
---- a/luci-app-ua2f/Makefile
-+++ b/luci-app-ua2f/Makefile
-@@ -2,7 +2,7 @@
- include $(TOPDIR)/rules.mk
+--- a/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
++++ b/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
+@@ -261,6 +261,7 @@ return view.extend({
+ 					body.push(E('p', {}, E('label', { 'class': 'btn' }, [
+ 						opts.backup_pkgs[0], ' ', _('Include in backup a list of current installed packages at /etc/backup/installed_packages.txt')
+ 					])));
++					opts.backup_pkgs[0].checked = true;
+ 				};
  
- LUCI_TITLE:=ua2f for luci
--LUCI_DEPENDS:=
-+LUCI_DEPENDS:=+ua2f
- LUCI_PKGARCH:=all
- PKG_VERSION:=5.2
- PKG_RELEASE:=5
-
---- a/msmtp/Makefile
-+++ b/msmtp/Makefile
-@@ -46,7 +46,7 @@ endef
+ 				var cntbtn = E('button', {
+@@ -302,6 +303,10 @@ return view.extend({
+ 				opts.keep[0].addEventListener('change', function(ev) {
+ 					opts.skip_orig[0].disabled = !ev.target.checked;
+ 					opts.backup_pkgs[0].disabled = !ev.target.checked;
++					if (ev.target.checked == false){
++						opts.skip_orig[0].checked =false
++						opts.backup_pkgs[0].checked =false
++					}
  
- define Package/msmtp
- $(call Package/msmtp/Default)
--  DEPENDS+= +libgnutls +ca-bundle
-+  DEPENDS+= +libgnutls +ca-bundle +libopenssl
-   TITLE+= (with SSL support)
-   VARIANT:=ssl
-   DEFAULT_VARIANT:=1
+ 				});
  
- define Package/luci-app-homeassistant/conffiles
- /etc/config/homeassistant
-
---- a/k3screenctrl/Makefile
-+++ b/k3screenctrl/Makefile
-@@ -19,7 +19,7 @@ TARGET_CFLAGS+= -D_GNU_SOURCE
- define Package/k3screenctrl
-   SECTION:=utils
-   CATEGORY:=Utilities
--  DEPENDS:=@(TARGET_bcm53xx_generic_DEVICE_phicomm_k3||TARGET_bcm53xx_generic_DEVICE_phicomm-k3||TARGET_bcm53xx_DEVICE_phicomm-k3) +@KERNEL_DEVMEM +coreutils +coreutils-od +bash +curl
-+  DEPENDS:=@(TARGET_bcm53xx_generic_DEVICE_phicomm_k3||TARGET_bcm53xx_generic_DEVICE_phicomm-k3||TARGET_bcm53xx_DEVICE_phicomm-k3||TARGET_DEVICE_bcm53xx_generic_DEVICE_phicomm_k3) +@KERNEL_DEVMEM +coreutils +coreutils-od +bash +curl
-   TITLE:=LCD screen controller on PHICOMM K3
-   URL:=https://github.com/lwz322/k3screenctrl.git
- endef
-
---- a/dockerd/Makefile
-+++ b/dockerd/Makefile
-@@ -47,6 +47,8 @@ define Package/dockerd
-     +kmod-veth \
-     +tini \
-     +uci-firewall \
-+    +fuse-overlayfs +cgroupfs-mount \
-+    +kmod-vxlan +kmod-macvlan +kmod-dummy +kmod-crypto-gcm +kmod-crypto-seqiv +kmod-crypto-ghash +kmod-ipsec +kmod-nf-nathelper +kmod-nf-nathelper-extra +btrfs-progs \
-     @!(mips||mipsel)
-   USERID:=docker:docker
-   MENU:=1
-@@ -95,13 +96,13 @@ define Build/Prepare
- 	$(Build/Prepare/Default)
- 
- 	# Verify dependencies are the vendored version
--	$(call EnsureVendoredVersion,../containerd/Makefile,containerd.installer)
--	$(call EnsureVendoredVersion,../runc/Makefile,runc.installer)
--	$(call EnsureVendoredVersion,../tini/Makefile,tini.installer)
-+	$(call EnsureVendoredVersion,../../packages/utils/containerd/Makefile,containerd.installer)
-+	$(call EnsureVendoredVersion,../../packages/utils/runc/Makefile,runc.installer)
-+	$(call EnsureVendoredVersion,../../packages/utils/tini/Makefile,tini.installer)
- 
- 	# Verify CLI is the same version
- 	( \
--		CLI_MAKEFILE="../docker/Makefile"; \
-+		CLI_MAKEFILE="../../packages/utils/docker/Makefile"; \
- 		CLI_VERSION=$$$$( grep --only-matching --perl-regexp '(?<=PKG_VERSION:=)(.*)' "$$$${CLI_MAKEFILE}" ); \
- 		if [ "$$$${CLI_VERSION}" != "$(PKG_VERSION)" ]; then \
- 			echo "ERROR: Expected 'PKG_VERSION:=$(PKG_VERSION)' in '$$$${CLI_MAKEFILE}', found 'PKG_VERSION:=$$$${CLI_VERSION}'"; \
-
---- a/fullconenat/Makefile
-+++ b/fullconenat/Makefile
-@@ -36,7 +36,7 @@ define Package/ip6tables-mod-fullconenat
-   SECTION:=net
-   CATEGORY:=Network
-   TITLE:=FULLCONENAT ip6tables extension
--  DEPENDS:=ip6tables +kmod-nf-nat6 +kmod-ipt-fullconenat +ip6tables-mod-nat
-+  DEPENDS:=+ip6tables +kmod-nf-nat6 +kmod-ipt-fullconenat +ip6tables-mod-nat
- endef
- 
- define KernelPackage/ipt-fullconenat
-
---- a/phtunnel/Makefile
-+++ b/phtunnel/Makefile
-@@ -36,7 +36,6 @@ PKG_SOURCE:=phtunnel
- PKG_SOURCE_URL:=https://mirrors.oray.com/orayos/packages/$(PKG_NAME)/$(PKG_ARCH_PHT)/$(PKG_VERSION)/bin
- PKG_HASH:=skip
- 
--PKG_FLAGS:=nonshared
- PKG_MAINTAINER:=Oray <developer@oray.com>
- 
- include $(INCLUDE_DIR)/package.mk
-
---- a/pgyvpn/Makefile
-+++ b/pgyvpn/Makefile
-@@ -36,7 +36,6 @@ PKG_SOURCE:=pgyvpnsvr
- PKG_SOURCE_URL:=https://mirrors.oray.com/orayos/packages/$(PKG_NAME)/$(PKG_ARCH_PGYYPN)/$(PKG_VERSION)/bin
- PKG_HASH:=skip
- 
--PKG_FLAGS:=nonshared
- PKG_MAINTAINER:=Oray <developer@oray.com>
- 
- include $(INCLUDE_DIR)/package.mk
-
---- a/wifidog-wiwiz/Makefile
-+++ b/wifidog-wiwiz/Makefile
-@@ -21,7 +21,7 @@ define Package/wifidog-wiwiz
-   SUBMENU:=Portal
-   SECTION:=net
-   CATEGORY:=Wiwiz/PinPinWiFi
--  DEPENDS:=+iptables-mod-extra +iptables-mod-ipopt +iptables-mod-nat-extra +libpthread +curl
-+  DEPENDS:=+luci-app-eqos +dcc2-wiwiz-nossl +iptables-mod-extra +iptables-mod-ipopt +iptables-mod-nat-extra +libpthread +curl
-   TITLE:=wifidog-wiwiz
-   URL:=http://www.wiwiz.com
-   MENU:=1
-
---- a/luci-app-rclone/Makefile
-+++ b/luci-app-rclone/Makefile
-@@ -15,7 +15,7 @@ PKG_CONFIG_DEPENDS:= \
- 
- LUCI_TITLE:=LuCI support for Rclone
- LUCI_PKGARCH:=all
--LUCI_DEPENDS:=+rclone-config \
-+LUCI_DEPENDS:=+rclone-config +fuse-overlayfs +fuse3-utils \
- 	+PACKAGE_$(PKG_NAME)_INCLUDE_rclone-webui:rclone-webui-react \
- 	+PACKAGE_$(PKG_NAME)_INCLUDE_rclone-ng:rclone-ng
-
---- a/luci-app-advancedplus/Makefile
-+++ b/luci-app-advancedplus/Makefile
-@@ -7,7 +7,7 @@ include $(TOPDIR)/rules.mk
- NAME:=advancedplus
- PKG_NAME:=luci-app-$(NAME)
- LUCI_TITLE:=LuCI support for Kucat theme setting by sirpdboy
--LUCI_DEPENDS:=+luci-compat +curl +wget +libustream-openssl
-+LUCI_DEPENDS:=+luci-compat +curl
- LUCI_PKGARCH:=all
- 
- PKG_VERSION:=1.8.0
-
---- a/luci-app-einat/Makefile
-+++ b/luci-app-einat/Makefile
-@@ -9,7 +9,7 @@ LUCI_NAME:=luci-app-einat
- 
- LUCI_TITLE:=LuCI Support for einat
- LUCI_PKGARCH:=all
--LUCI_DEPENDS:=
-+LUCI_DEPENDS:=+einat-ebpf
- 
- LUCI_DESCRIPTION:=eBPF-based Endpoint-Independent NAT
