update

diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic b/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
--- a/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
@@ -4,7 +4,7 @@
 # Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
 #======================================================================================
-
+#
 # The script supports directly setting parameters for installation, skipping interactive selection
 # openwrt-install-amlogic ${AUTO_MAINLINE_UBOOT} ${ID} ${FDTFILE}:${SOC}:${UBOOT_OVERLOAD} ${SHARED_FSTYPE}
 # E.g: openwrt-install-amlogic yes 11 auto ext4
@@ -14,6 +14,28 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-install-amlogic
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
 
 # Receive one-key command related parameters
 AUTO_MAINLINE_UBOOT="${1}"
@@ -35,8 +57,7 @@ SPECIFY_UBOOT=""
             SPECIFY_SOC="$(echo "${3}" | awk -F ':' '{print $2}')"
             SPECIFY_UBOOT="$(echo "${3}" | awk -F ':' '{print $3}')"
         else
-            echo "Please enter the DTB file name!"
-            exit 1
+            error_msg "Please enter the DTB file name!"
         fi
     fi
 }
@@ -53,30 +74,23 @@ echo "SHARED_FSTYPE: ${SHARED_FSTYPE}"
 # Current device model
 MYDEVICE_NAME=$(cat /proc/device-tree/model | tr -d '\000')
 if [[ -z "${MYDEVICE_NAME}" ]]; then
-    echo "The device name is empty and cannot be recognized."
-    exit 1
+    error_msg "The device name is empty and cannot be recognized."
 elif [[ ! -f "${op_release}" ]]; then
-    echo "The [ ${op_release} ] file is missing."
-    exit 1
+    error_msg "The [ ${op_release} ] file is missing."
 else
     echo -e "Current device: ${MYDEVICE_NAME} [ amlogic ]"
     sleep 3
 fi
 
 # Find the device name of /
-root_devname=$(df / | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')
-if [[ -z "${root_devname}" ]]; then
-    root_devname="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')"
-fi
+root_devname="$(get_root_partition_name)"
 if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
-    echo "you are running in emmc mode, please boot system with usb or tf card!"
-    exit 1
+    error_msg "you are running in emmc mode, please boot system with usb or tf card!"
 fi
 
 install_emmc="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")"
 if [[ "${install_emmc}" == "" ]]; then
-    echo "No emmc can be found to install the openwrt system!"
-    exit 1
+    error_msg "No emmc can be found to install the openwrt system!"
 fi
 
 # EMMC DEVICE NAME
@@ -110,19 +124,28 @@ echo "BOOT: ${BOOT_NAME}"
 if [[ -f "/etc/model_database.txt" ]]; then
     model_database="$(cat /etc/model_database.txt)"
 else
-    echo "[ /etc/model_database.txt ] file is missing."
-    exit 1
+    error_msg "[ /etc/model_database.txt ] file is missing."
 fi
 
 function display_database() {
-    echo "${model_database}" | perl -ne 'chomp;if(m/^#/){s/#+\s+//;print "$_ >>>\n";}elsif($_){@f=split/:/;printf("%4s. %-30s%-8s%-s\n",$f[0],$f[1],$f[2],$f[7])}'
+    while read -r line; do
+        if [[ "$line" =~ ^# ]]; then
+            # Process comment lines, starting with #
+            line="${line/#+\s+/}"
+            echo "$line >>>"
+        else
+            # Process data lines, starting with id
+            IFS=':' read -r -a fields <<<"$line"
+            printf "%5s %-48s%-10s%-s\n" "${fields[0]}" "${fields[1]}" "${fields[2]}" "${fields[7]}"
+        fi
+    done < <(echo "${model_database}")
 }
 
 function search_model() {
     local id="${1}"
     local ret_count="$(echo "${model_database}" | awk -F ':' "\$1~/^$id\$/ {print \$0}" | wc -l)"
     if [[ "${ret_count}" -eq "1" ]]; then
-        echo "${model_database}" | awk -F ':' "\$1~/^$id\$/ {print \$0}"
+        echo "${model_database}" | awk -F ':' "\$1~/^$id\$/ {print \$0}" | sed -e 's/NA//g' -e 's/NULL//g' -e 's/[ ][ ]*//g'
     fi
 }
 
@@ -164,24 +187,22 @@ elif [[ "${boxtype}" -eq "0" ]]; then
 else
     ret="$(search_model ${boxtype})"
     if [[ -z "${ret}" ]]; then
-        echo "Input error, exit!"
-        exit 1
+        error_msg "Input error, exit!"
     fi
     # 3.  soc
     # 4.  FDTFILE
     # 5.  UBOOT_OVERLOAD
     # 6.  MAINLINE_UBOOT
     # 7.  ANDROID_UBOOT
-    AMLOGIC_SOC="$(echo "${ret}" | awk -F ':' '{print $3}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')"
-    FDTFILE="$(echo "${ret}" | awk -F ':' '{print $4}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')"
-    UBOOT_OVERLOAD="$(echo "${ret}" | awk -F ':' '{print $5}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')"
-    MAINLINE_UBOOT="$(echo "${ret}" | awk -F ':' '{print $6}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')"
-    ANDROID_UBOOT="$(echo "${ret}" | awk -F ':' '{print $7}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')"
+    AMLOGIC_SOC="$(echo "${ret}" | awk -F ':' '{print $3}')"
+    FDTFILE="$(echo "${ret}" | awk -F ':' '{print $4}')"
+    UBOOT_OVERLOAD="$(echo "${ret}" | awk -F ':' '{print $5}')"
+    MAINLINE_UBOOT="$(echo "${ret}" | awk -F ':' '{print $6}')"
+    ANDROID_UBOOT="$(echo "${ret}" | awk -F ':' '{print $7}')"
 fi
 
 if [[ -z "${FDTFILE}" || ! -f "/boot/dtb/amlogic/${FDTFILE}" ]]; then
-    echo "/boot/dtb/amlogic/${FDTFILE} does not exist!"
-    exit 1
+    error_msg "/boot/dtb/amlogic/${FDTFILE} does not exist!"
 fi
 
 echo "AMLOGIC_SOC Value [ ${AMLOGIC_SOC} ]"
@@ -243,8 +264,7 @@ for mnt in $MOUNTS; do
         echo "umount -f $mnt"
         umount -f $mnt
         if [ $? -ne 0 ]; then
-            echo "$mnt Cannot be uninstalled, the installation process is aborted."
-            exit 1
+            error_msg "$mnt Cannot be uninstalled, the installation process is aborted."
         fi
     fi
 done
@@ -264,7 +284,13 @@ done
 # you can change ROOT size(MB) >= 320
 ROOT1="960"
 ROOT2="960"
-if [[ "${AMLOGIC_SOC}" == "s912" || "${AMLOGIC_SOC}" == "s905d" ]]; then
+if [[ "${AMLOGIC_SOC}" == "s912" ]] && [[ "${boxtype}" == "213" || "${boxtype}" == "2e" ]]; then
+    BOOT="512"
+    BLANK1="700"
+    BLANK2="220"
+    BLANK3="0"
+    BLANK4="0"
+elif [[ "${AMLOGIC_SOC}" == "s912" || "${AMLOGIC_SOC}" == "s905d" ]]; then
     BOOT="512"
     BLANK1="68"
     BLANK2="220"
@@ -479,8 +505,7 @@ while [ $i -le $max_try ]; do
             echo "Not mounted successfully, try again ..."
             i=$((i + 1))
         else
-            echo "Cannot mount the boot file system, give up!"
-            exit 1
+            error_msg "Cannot mount the boot file system, give up!"
         fi
     else
         echo "Successfully mounted."
@@ -532,8 +557,7 @@ while [ $i -le $max_try ]; do
             echo "Not mounted successfully, try again ..."
             i=$((i + 1))
         else
-            echo "Cannot mount rootfs file system, give up!"
-            exit 1
+            error_msg "Cannot mount rootfs file system, give up!"
         fi
     else
         echo "Successfully mounted"
@@ -572,14 +596,13 @@ while [ $i -le $max_try ]; do
    ]
 }
 EOF
+
         # change data_root value in /etc/config/dockerd
-        if [ -f ./etc/init.d/dockerman ] && [ -f ./etc/config/dockerd ]; then
-            tmp_dockerd=$(mktemp)
-            perl -npe "s/option data_root '.+'/option data_root '\/mnt\/${EMMC_NAME}p4\/docker\/'/" ./etc/config/dockerd >${tmp_dockerd} && mv ${tmp_dockerd} ./etc/config/dockerd
-            unset tmp_dockerd
+        if [[ -f "/etc/init.d/dockerman" ]] && [[ -f "/etc/config/dockerd" ]]; then
+            sed -i "s|option data_root.*|option data_root '/mnt/${EMMC_NAME}p4/docker/'|g" /etc/config/dockerd
         fi
-        rm -rf opt/docker && ln -sf /mnt/${EMMC_NAME}p4/docker/ opt/docker >/dev/null
-        rm -rf usr/bin/AdGuardHome && ln -sf /mnt/${EMMC_NAME}p4/AdGuardHome usr/bin/ >/dev/null
+        rm -rf /opt/docker && ln -sf /mnt/${EMMC_NAME}p4/docker/ /opt/docker >/dev/null
+        rm -rf /usr/bin/AdGuardHome && ln -sf /mnt/${EMMC_NAME}p4/AdGuardHome /usr/bin/ >/dev/null
 
         echo "Edit configuration file ..."
         #cd /mnt/${EMMC_NAME}p2/usr/bin/
@@ -610,7 +633,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${ROOTFS1_UUID}'
         option enabled '1'
         option enabled_fsck '1'
